name: Build

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          package: ["charmcraft", "rockcraft", "snapcraft"]
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: jnsgruk
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    
      - name: Build ${{ matrix.package }}
        run: nix build .#${{ matrix.package }}