name: "Cachix"
on:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout flake
        uses: actions/checkout@v3

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: jnsgruk
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build packages
        run: nix build .#charmcraft .#snapcraft .#rockcraft
