name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  # build:
  #   uses: ./.github/workflows/build.yaml
  #   secrets:
  #     CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  # test:
  #   uses: ./.github/workflows/test.yaml
