name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          package: ["charmcraft", "rockcraft", "snapcraft"]
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build and run the test VM
        run: |
          nix run .#testVm -- -daemonize -display none

      - name: Test ${{ matrix.package }}
        run: |
          nix run .#testVmExec -- craft-test ${{ matrix.package }}
